{% set name = "semver" %}
{% set version = "3.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14bc073439513d7773662a338f4db9829cf16c12b74b9568e2d2689975fbd7fc

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pysemver = semver.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools >=61
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - semver
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests
    - pysemver -h

about:
  home: https://github.com/python-semver/python-semver
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/python-semver/python-semver
  doc_url: https://github.com/python-semver/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
  skip-lints:
    # source url is reachable
    - reachable_url
