{% set name = "semver" %}
{% set version = "2.13.0" %}
{% set sha256sum = "fa0fe2722ee1c3f57eac478820c3a5ae2f624af8264cbdf9000c980ff7f75e3f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - semver

about:
  home: https://github.com/k-bx/python-semver
  license: BSD
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
