travis:
  secure:
    BINSTAR_TOKEN: H/PXArepVwCbTtz/io9R3gniDce14eiewtUWSwaoil4RsKHvES/Nj5JfYnuIreMFinlmPTqrOVz5IzDzwtN71krZV/HUIVWVix3/s23aoz2xj7xIeJuQhsCMpuwSGGS4euVSpFC74imLdn4cPV4ohuCVq3xv/Z3aO2/fMiEWy+NssjMpbjEb9Xf76qyu8/Xp6chNKWwsNMpT/Yw6M/1H9IOxWoa6MlV+wiHEj53o82LOdo5wRNimBTTKlAO4QjSuFNeAGxZ20v6ScAdMQT2tFYZGC1diBMqHaGsJr/ayqH/DmUh8oxSPVBMFSbhVZge6jzEuQ8IzPzY4N/U2cXC+5mVoLHjr6JOa/e5KUFi+1m33tEefNSgdeVLkw6D7A7HteRBp0Q7vfFStqZUD/12wBPyQU5XVhqdZ7vY8XTGA6lZLN51yPJTnb42URIy+eo/AbsfrSaIg1dJxk5h4RcKGCHulZnS5fMATQF1+QMPk5rrO3tivGUXVE93wBebnk0lbCwbYlxtRDhtTT57OdtMHwo95dfmhkLeXCdteQGGZ0qCD1obvHN6tBIkhAHcjAmxOjndIDJXKW+5/sgSYdzpTr5AVml/T5JBFNAu5DLBKonyHFle1WlY2RzypAH6dHLMBI7DuNyKdgGlPuBkfMyE0Oc5PNfxGrd/yPqNAPcgjCV0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
