travis:
  secure:
    BINSTAR_TOKEN: R5XXOjqWGPTst3M2Wt2kKQY4X/mGngq07Kh/RCO7tOIKVQQug1E0fUi7rfpBwOXfXmn3dUF/OeX2AWUAoGsa0ERQI+qI0sZ07PFU658uiW2be9zPSiwJNiq7ZX4oV9pwerGCMWzDwuLBAAvOYrkI6wqsXK4dbXi/54bOUX1U4LL99gS6V1aTPekqRhHyDjbBbd/WTpI0x4VsthyZ2Ti0arbk2TiqUtBg0pBUS/Zg1g7aOhIMNDz+N9j3yQQzmPz4sicTajwsuHliB9aQ0keFxJZVveEYznrYY14l5W0WBqTcpsKSfw/eK8UMnIOorF53uKu/RcDxLR8Pcu494mBlCh+zBo8a0BZVdZmsGKYctse2SbKUk0AqUBu+J2MoMLCzaGNqF0pQgv7Z+ERJTHrXs6qlokBqJShgImcbSm0FkUcO7y8xqylDiT8qg6Z4zDRHfXES4SakR5DO4zxX/jclAxJ2XjKMtpiBk5dlRClKDtrL6vGLdLLB+QoPh8PhGPjEgxhDYFaQEZPZbI65QgJpD6p9c7MGyx2E8MhkSk6VWpm1//R9qZ37DmILm4Lbe8c24COZGf17pYKcd87DJj8e5BqdWUY2SOfh72Wx2v24f1Blwl01FAE6klvBUXawKVNMzGLJPxJKMmYTRb76oFM1LYmiGqJRu9ZdhBNgojqO4aM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
