travis:
  secure:
    BINSTAR_TOKEN: Ie4nNmcm3f4B7f2YGeH1gJmpaLWfaCRgtTV1vxf1JiHtLqFXln9JyAzbK3MZg3/NlY68JnjzSd3krX4ZsIV+LwGY9kZBtrSd1stCX8UaOoE2FcHYuCIPQdFH0WrfzT3bPWlZ7v7Pss6hDVJrR7ojqnHbItHBSn41tkVEiLGUL1S00wgXsAWkQFaGlzcb/OJyw7zqhJg+tBiU1A5iXspZbayQMYm+TKJaYWQ4+r1DOkdXbO3HYZzGcHNH2fzuy3ThrL7NRJ5EdQyshSxF0Nvt2MLPftJa6WMeW8Enhm9baFM19fW7Wm9dbR/mSbuyujJPjlhimTFY9aiGIqCz0B89mBKzkXsT4XaCDb5pWZgLeqU59kecuHrcayy4FQAxakFYTp5P8iEFgE6xWm15PGM7Lw7/4l/AsTfw6+/x4hcrpeBx494Fqo6qfTY3H2iuR+dampQd73A+Yf77xm0XnMjCodhOCOlWPZH3hlVMaZfBHEGCv6H0YPrcYj1Ao9GlSP0Ywhe1v8BQdUClp1wHXMGfohArhdZNVcAXljXcO+6qC5kMWcLMN0nAeNjz8nMv6858CSFPap82BUL8D9AqLRacfGSsSKcXYQ5x+wVabqstRYF7h9by02gfNQcsakHugQNCaTo5TIlYJK/yhApDaVN5ox+9PUbpZa+4cDMvXy1clS4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
